#!/usr/bin/env python3
"""
RENDER DATABASE PSQL CONNECTION GUIDE
Complete instructions to fix the missing v_credit_balance view
"""

print("🚨 EMERGENCY DATABASE VIEW FIX - RENDER PSQL METHOD")
print("=" * 60)
print()
print("🎯 PROBLEM: ERROR: relation 'v_credit_balance' does not exist")
print()
print("📋 LÖSUNG - 3 METHODEN:")
print("-" * 40)
print()
print("METHOD 1: PSQL COMMAND LINE (EMPFOHLEN)")
print("1. Gehe zu https://dashboard.render.com/")
print("2. Wähle deine PostgreSQL Database")
print("3. Klicke 'Connect' Button (oben rechts)")
print("4. Kopiere 'PSQL Command' ")
print("5. Führ den Command in deinem Terminal aus")
print("6. Führ diesen SQL-Befehl aus:")
print()
print("   CREATE OR REPLACE VIEW v_credit_balance AS")
print("   SELECT user_id, COALESCE(SUM(delta), 0) AS balance")
print("   FROM credit_ledger GROUP BY user_id;")
print()
print("-" * 40)
print("METHOD 2: pgAdmin (WEB INTERFACE)")
print("1. Gehe zu deiner Database in Render Dashboard")
print("2. Gehe zu 'Apps' Tab")
print("3. Klicke 'Deploy app' bei pgAdmin")
print("4. Nach Deploy: Klicke 'Open app'")
print("5. Login mit generierten Credentials")
print("6. Führe den SQL-Befehl in pgAdmin aus")
print()
print("-" * 40)
print("METHOD 3: External Tool")
print("1. Kopiere 'External URL' von deiner Database")
print("2. Verbinde mit Tool wie DBeaver/TablePlus")
print("3. Führe den SQL-Befehl aus")
print()
print("-" * 40)
print()
print("🎯 SQL BEFEHL ZUM AUSFÜHREN:")
print("CREATE OR REPLACE VIEW v_credit_balance AS")
print("SELECT user_id, COALESCE(SUM(delta), 0) AS balance")
print("FROM credit_ledger GROUP BY user_id;")
print()
print("✅ Nach Ausführung: Credits-System funktioniert sofort!")
