-- Update Prisma database with new Stripe Price IDs
-- Generated by setup-stripe.js script

INSERT INTO prices (stripe_price_id, credits_per_unit, price_in_cents, currency, active)
VALUES ('price_1S2vWOEPwuWwkzKTTYW2QNMN', 100, 500, 'eur', true)
ON CONFLICT (stripe_price_id) DO UPDATE SET
  credits_per_unit = 100,
  price_in_cents = 500,
  active = true;

INSERT INTO prices (stripe_price_id, credits_per_unit, price_in_cents, currency, active)
VALUES ('price_1S2vWPEPwuWwkzKTPwUwNUWx', 500, 2000, 'eur', true)
ON CONFLICT (stripe_price_id) DO UPDATE SET
  credits_per_unit = 500,
  price_in_cents = 2000,
  active = true;

INSERT INTO prices (stripe_price_id, credits_per_unit, price_in_cents, currency, active)
VALUES ('price_1S2vWPEPwuWwkzKTOM5Bywim', 1000, 3500, 'eur', true)
ON CONFLICT (stripe_price_id) DO UPDATE SET
  credits_per_unit = 1000,
  price_in_cents = 3500,
  active = true;

INSERT INTO prices (stripe_price_id, credits_per_unit, price_in_cents, currency, active)
VALUES ('price_1S2vWPEPwuWwkzKTYN57r165', 2500, 7500, 'eur', true)
ON CONFLICT (stripe_price_id) DO UPDATE SET
  credits_per_unit = 2500,
  price_in_cents = 7500,
  active = true;
