name: Backend Deploy (Render)

on:
  push:
    branches: [ security-hardening-neon ]
    paths:
      - 'apps/backend/**'
      - 'render.yaml'
      - 'apps/backend/requirements.txt'
      - 'apps/backend/pyproject.toml'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: backend-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger via Deploy Hook
        env:
          HOOK: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK_URL not set; skipping" && exit 78
          fi
          echo "Triggering Render deploy hook..."
          curl -sS -X POST "$HOOK" -o /dev/null -w "%{http_code}\n"

      - name: Done
        run: echo "Render deploy step finished"
